FROM fiware/orion-ld-base

ARG PATH_TO_SRC='opt/orion/'

RUN yum -y install hostname && \
    cp -a /usr/local/lib/. /usr/lib/x86_64-linux-gnu/ && \
    rm -r /usr/local/lib/

COPY . ${PATH_TO_SRC}

WORKDIR ${PATH_TO_SRC}

ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig

RUN make debug install

ENV LD_LIBRARY_PATH=/opt/paho.mqtt.c/build/output:/usr/local/lib64:/opt/prometheus-client-c/prom/build:/opt/prometheus-client-c/promhttp/build:/usr/lib/x86_64-linux-gnu/

ENTRYPOINT ["orionld", "-fg", "-multiservice" ]

EXPOSE 1026
