FROM fiware/orion-ld-base

RUN echo "=================== /usr/local/lib/ =================================="
RUN ls /usr/local/lib/*.so*
RUN echo "======================================================================"

ARG PATH_TO_SRC='/opt/orion/'
WORKDIR ${PATH_TO_SRC}


ENV LD_LIBRARY_PATH=/opt/paho.mqtt.c/build/output:/usr/local/lib64:/opt/prometheus-client-c/prom/build:/opt/prometheus-client-c/promhttp/build:/usr/local/lib
# RUN echo LD_LIBRARY_PATH: $LD_LIBRARY_PATH
COPY docker/mongo.repo /etc/yum.repos.d/mongo.repo

RUN  wget https://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz && \
     tar -xf lcov-1.14.tar.gz  && \
     cd lcov-1.14 && \
     make install && \
     cd .. && \
     yum install -y gnupg && \
     yum install -y mongodb-database-tools mongodb-org-database-tools-extra \
                 mongodb-org-tools mongodb-org-shell mongodb-org-server \
                 mongodb-org-mongos mongodb-org && \
     yum install -y python3 python2 virtualenv && \
     ln --force -s /usr/bin/python2 /usr/bin/python && \
     yum install -y openssl-devel libffi-devel netcat bc diffutils hostname procps gmock-devel gtest && \
     wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && \
     python2.7 get-pip.py && \
     pip2.7 install Flask && \
     pip2.7 install paho-mqtt && \
     pip2.7 install pyopenssl && \
     wget https://src.fedoraproject.org/repo/pkgs/gmock/gmock-1.5.0.tar.bz2/d738cfee341ad10ce0d7a0cc4209dd5e/gmock-1.5.0.tar.bz2 && \
     tar xfvj gmock-1.5.0.tar.bz2 && \
     cd gmock-1.5.0 && \
     ./configure && \
     make && \ 
     make install && \
     cd .. && \
     yum clean all && \
     rm lcov-1.14.tar.gz gmock-1.5.0.tar.bz2 


COPY . ${PATH_TO_SRC}
WORKDIR ${PATH_TO_SRC}

ENTRYPOINT ["docker/build.sh"]
